### ISSUE TITLE
[Bug] 조회수 관련

### ISSUE THREAD

**Issue by pione3r** [in-seo/SouP#15]
로그인을 한 상태에서 본인이 작성한 게시글을 방문하면 조회수가 2씩 증가하는 버그가 있습니다.

아래 코드에서 addViews를 호출할 때, 조회수가 2씩 증가하는 것 같습니다.

https://github.com/in-seo/SouP/blob/e54f90b6e5d6e76bdb6e0027199685f06e159579/SouP/src/main/java/Matching/SouP/domain/post/Post.java#L80C1-L81C1

**Comment by pione3r** [comment]
try in ```/domain/post/Post.java```
```java
    public void addViews() {views+=1;}
```

**Comment by in-seo** [comment]
@pione3r  오픈 초기에 사용자가 많아보일라고 꼼수를 좀 썼었습니다.... :)  감사합니다
